version: "3.8"
services:
  api:
    build: .
    depends_on:
      - dragonfly
    environment:
      REDIS_HOST: dragonfly
    networks:
      - femme-network
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    networks:
      - femme-network
networks:
  femme-network:
    driver: bridge
volumes:
  dragonflydata:
